# Generated by Django 4.0.3 on 2022-04-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hdd_ssd_processor_image_product_operative_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_cd_drive',
            field=models.BooleanField(default=False),
        ),
    ]
