# Generated by Django 4.0.3 on 2022-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('description', models.CharField(max_length=500)),
                ('products', models.ManyToManyField(blank=True, db_index=True, null=True, related_name='games', to='core.product')),
            ],
        ),
    ]
