# Generated by Django 4.0.3 on 2022-04-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_game_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='productversion',
            options={'verbose_name': 'ProductVersion', 'verbose_name_plural': 'ProductVersions'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
