# Generated by Django 4.0.3 on 2022-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_game_options_alter_productversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='color',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
