# Generated by Django 4.0.3 on 2022-05-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_productversion_color'),
        ('core', '0015_news'),
    ]

    operations = [
    ]
