# Generated by Django 4.0.3 on 2022-05-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_card',
        ),
    ]
