# Generated by Django 4.0.3 on 2022-05-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
