# Generated by Django 4.0.3 on 2022-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_productversion_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Price'),
        ),
    ]
