# Generated by Django 4.0.3 on 2022-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_productversion_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email adress')),
                ('delivery', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('Nəğd', 'Nəğd'), ('Kartla', 'Kartla')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
